stages:
  - build
  - docker

build:
  stage: build
  image: docker.finogeeks.club/base/node:14.15.3-alpine
  script:
  - rm package-lock.json
  - npm install --registry=https://registry.npm.taobao.org
  only:
    - tags
  except:
    - branches

docker:
  stage: docker
  image: docker.finogeeks.club/mop/kaniko-executor:debug
  script:
  - mkdir -p /kaniko/.docker
  - echo "${DOCKER_AUTH_CONFIG}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination docker.finogeeks.club/mop/enterprise-service-node:$CI_COMMIT_TAG --build-arg MONGO_URL=mongodb://Lc9E0nb:ocmq92#mcOCK!q19vLpq@mongo-cluster-0.mongo-cluster.storage:27017,mongo-cluster-1.mongo-cluster.storage:27017,mongo-cluster-2.mongo-cluster.storage:27017/sgb-service?replicaSet=rs0&authSource=admin
  only:
    - tags
  except:
    - branches